# Generated by Django 4.2.6 on 2023-11-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='symbol',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
