# Generated by Django 4.2.6 on 2023-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='game_played',
            field=models.IntegerField(default=0),
        ),
    ]
