# Generated by Django 4.2.6 on 2023-12-10 23:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_game_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='symbol',
            field=models.CharField(default=users.models.generate_default_symbol, max_length=2),
        ),
    ]
