# Generated by Django 4.2.6 on 2023-11-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_game_delete_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='alignement',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='game',
            name='grid_size',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
