# Generated by Django 4.2.6 on 2023-11-18 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_rename_alignement_game_win_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
