# Generated by Django 4.2.6 on 2023-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_game_game_author_alter_game_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
