# Generated by Django 4.2.6 on 2023-12-10 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_game_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('symbol', models.CharField(default=' ', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.game')),
            ],
        ),
    ]
