# Generated by Django 4.2.6 on 2023-12-11 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_gridcell'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='currentTurn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gridcell',
            name='symbol',
            field=models.CharField(max_length=2),
        ),
    ]
