# Generated by Django 4.2.6 on 2023-12-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_game_currentturn_alter_gridcell_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='abandonned',
            field=models.BooleanField(default=False),
        ),
    ]
